### ISSUE TITLE
🚧Improve release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#100]
### Complete The Item Below

- [x] I have updated the title without removing the 🚧 emoji.

### Description

Improve the release workflow:
1. Add a step to the `validate_release` job to check if the JSR package has already been released
    - This will use the [JSR Registry API](https://jsr.io/docs/api#jsr-registry-api) with deno to check if the package of a certain version does not already exist
    - The name of the step should be `JSR Package Version Does Not Exist`
    - The name of the script file should be _**jsr-pkg-version-does-not-exist.ts**_
2. Add a step to the `validate_release` job to check if a GitHub release does not already exist
    - The name of the step should be `GitHub Does Not Exist`
    - The name of the script file name should be `github-release-does-not-exist.ts`
4. Update the _**check-release-notes.ts**_ script to trim the `v` from the version before use    - The letter `v` still needs to be included in the release notes file path
3. Remove the _**deno-check.ts**_ file
4. Remove the deno check launch config from the _**launch.json**_
5. Remove the deno check task from the _**tasks.json**_ file
6. Setup a close milestone step in the `release` job
    - This will require a script to run
7. Rename the `Version Does Not Exist` step to `Tag Does Not Exist`
8. Rename the _**version-checker.ts**_ script file name to _**tag-does-not-exist.ts**_
10. Convert all cicd scripts to use environment variables instead of script args   - This is for security reasons 

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after the PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] Added a step to the `validate_release` job to check if the JSR package had already been released
- [x] Added a step to the `validate_release` job to check if a GitHub release does not already exist
- [x] Updated the _**check-release-notes.ts**_ script to trim the `v` from the version before use
- [x] Validate milestone exists script and step created
- [x] Combine all of the `validate_release` step results into a single final step
- [x] Removed the _**deno-check.ts**_ file
- [x] Removed the deno check launch config from the _**launch.json**_
- [x] Removed the deno check task from the _**tasks.json**_ file
- [x] Set up a close milestone step in the `release` job
- [x] The step `Version Does Not Exist` has been renamed
- [x] The file _**version-checker.ts**_ file has been renamed
- [x] Converted all cicd scripts to use environment variables instead of script args
- [x] The `File` class has been removed and references updated
- [x] The `Directory` class has been removed and references updated
- [x] Add imports to deno.json and convert imports
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.
