### ISSUE TITLE
🚧Add rate limiting

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#101]
### Complete The Item Below

- [x] I have updated the title without removing the 🚧 emoji.

### Description

When performing requests, we are hitting [secondary rate limits](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secondary-rate-limits).

This was discovered when trying to get all of the prs for a repository that has a very large amount of prs.  

> [!Note]
> The repository being used when this was discovered was the _**facebook/react**_ repository.

Based on the docs related to primary rate limits, add a rate-limiting feature to the `GitHubClient`.  This should keep track to requests over time that follows the documentation on primary rate limits.

Based on the docs related to secondary rate limits, add a rate-limiting feature to the `GitHubClient`.  In this `abstract` class, keep track of how many points as requests are being made. While requests are processed, the points are increased, and the points are decreased when the requests are finished.

## [1. Pause between mutative requests](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#pause-between-mutative-requests)
If you are making a large number of POST, PATCH, PUT, or DELETE requests, wait at least one second between each request. This will help you avoid secondary rate limits.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [ ] All the unit tests have been executed and passed locally after the PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [ ] The `GitHubClient` class has been modified to limit requests for primary rate limiting
- [ ] The `GitHubClient` class has been modified to limit requests for secondary rate limiting
- [ ] Requests are paused between other requests when mutative
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.
