### ISSUE TITLE
🚧Improve pull request client

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#11]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Improve the pull request client by updating the function to request reviewers for a pull request.  Currently, the function only requests a single reviewer at a time.  This is not ideal in situations where you have multiple reviewers to assign because you would need to use a loop to perform a request for each reviewer.  

The GitHub REST API endpoint has the ability to send multiple reviewers, but the function/client is simply not taking advantage of it.

**What to do:**
1. Refactor the name of the `requestReviewer` function to `requestReviewers`
2. Refactor the `requestReviewer` parameter named `reviewer` to the name `reviewers`
3. Change the `reviewer` parameter type from `string` to `string | string[]`.
    > **Note**
    > This will internally always send an array.  This is just to make it easy for the user

> **Note**
> The name of the class to make these changes is _**PullRequestClient**_

> **Warning**
> This introduces https://github.com/KinsonDigital/kd_clients/labels/%F0%9F%A7%A8breaking%20changes

### Acceptance Criteria

asdf

### ToDo Items

- [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
