### ISSUE TITLE
🚧Create prepare release workflow

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#14]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a workflow that helps prepare the release by creating the release notes and updating the version.  Use the prepare release workflow from the _**Velaptor**_ repository as a starting point.

The updating of the version will have to be done differently than in **Velaptor**.  It exists in the _**deno.json**_.  Currently the _**PrepareReleaseRunner**_ in the _**Infrastructure**_ repository needs to be updated to pull versions from deno files before this can be implemented.

Also, update the applicable workflows that use the `pull_request_target` trigger to use the preview branch in addition to the main branch.

With the creation of a preview branch, the release workflow will probably need to be updated.

> **Note**
> This is going to require this project to start using preview branches.

```[tasklist]
### Acceptance Criteria
- [x] A prepare release workflow created
- [x] Prepare release template file created
- [x] Required repo variables setup for project
- [x] Trigger updated to use the preview branch for _**build-status-check**_ workflow
- [x] Trigger updated to use the preview branch for _**lint-status-check**_ workflow
- [x] Trigger updated to use the preview branch for _**sync-status-check**_ workflow
- [x] Trigger updated to use the preview branch for _**test-status-check**_ workflow
- [x] Release workflow updated to work with preview branches for preview releases
- [x] Create `PROJECT_TYPE` repo variable to replace org version
- [x] Change repo variable `PR_RELEASE_TEMPLATE_BRANCH_NAME` value back to `preview`
- [x] Set default branch back to `main`
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Issue Dependencies

- KinsonDigital/Infrastructure#172

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
