### ISSUE TITLE
🚧Fix create org client issue

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#15]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When creating a new `OrgClient` object, an error is thrown that the `repoName` is null, undefined, or empty when it is not.

<details><summary>Error Details</summary>
<p>

```shell
error: Uncaught Error: The value is null, undefined, or empty.
Function Name: repoName
Param Name: v
			throw new Error(errorMsg);
			      ^
    at Function.isNothing (https://deno.land/x/kd_clients@v1.0.0-preview.4/core/Guard.ts:28:10)
    at OrgClient.set repoName (https://deno.land/x/kd_clients@v1.0.0-preview.4/core/GitHubClient.ts:64:9)
    at new GitHubClient (https://deno.land/x/kd_clients@v1.0.0-preview.4/core/GitHubClient.ts:27:16)
    at new OrgClient (https://deno.land/x/kd_clients@v1.0.0-preview.4/GitHubClients/OrgClient.ts:23:3)
    at AddItemToProjectRunner.validateArgs (file:///K:/SOFTWARE-DEV/PERSONAL/Infrastructure/cicd/scripts/runners/AddItemToProjectRunner.ts:78:21)
    at AddItemToProjectRunner.run (file:///K:/SOFTWARE-DEV/PERSONAL/Infrastructure/cicd/scripts/runners/ScriptRunner.ts:63:14)
    at AddItemToProjectRunner.run (file:///K:/SOFTWARE-DEV/PERSONAL/Infrastructure/cicd/scripts/runners/AddItemToProjectRunner.ts:35:15)
    at file:///K:/SOFTWARE-DEV/PERSONAL/Infrastructure/cicd/scripts/add-item-to-project.ts:4:32
```

</p>
</details> 

After digging into the issue, the org client is sending in an empty string literal into the `super()` call which is type `GitHubClient`.  In the `GitHubClient` class, the constructor contains a guard that checks if the `repoName` argument is null and throws an error when it is.  Which in this case it always is.

Just send in the value `na` to fix this issue.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] The bug in the `OrgClient` has been fixed
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
