### ISSUE TITLE
🚧Setup CICD and pr sync

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#2]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

This is the initial creation of the project.  Everything from code, config, ide settings, deno settings, etc.

### **Release Workflow**
The release workflow needs to be able to run linting, run tests, and then create an empty commit with a tag that is the version number.  This number should be chosen when manually running the release workflow. All validation of inputs should be performed.

### **Prepare Release Templates:**
Create new prepare release templates based on the ones that already exist in infrastructure.
Create these templates in this repo, not in the _**Infrastructure**_ repo. 

This will require the use of the following repo variables:
  - PREV_RELATIVE_PR_RELEASE_TEMPLATE_FILE_PATH
  - PROD_RELATIVE_PR_RELEASE_TEMPLATE_FILE_PATH
  - PR_RELEASE_TEMPLATE_REPO_NAME
    > **Note**
    > This variable will hold the name of the repo where the templates exist

### Acceptance Criteria

- [x] Setup PR syncing system
- [x] Build status check workflow created
    > **Note**
    > This uses the new `deno-check.ts` script
- [x] Setup test status check workflow
- [x] Setup linting status check workflow
- [x] Setup release workflow
    - [x] Runs linting
    - [x] Runs tests
    - [x] Creates an empty commit, tags that commit, and pushes all to remote
    - [x] Version validation run against the incoming workflow version input
    - [x] DENO_VERSION variable setup and used in all workflows
- [x] ~Prepare release templates created~
- [x] Packages vendored

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
It was decided not to set up the prepare release system.  It only works for c# projects.
