### ISSUE TITLE
🚧Add upload asset feature to release client

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#22]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the release client to give the ability to upload assets to an existing release.

Should have the following capabilities:
1. Upload a single asset
2. Upload multiple assets via an array of files
3. Check to make sure that the release exists first
4. Can take the _**title**_ of a release as a parameter when choosing a release to upload assets to

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Release client can upload a single asset to an existing release
- [x] Release client can upload multiple assets to an existing release
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
