### ISSUE TITLE
🚧Fix getting repo data bug

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#28]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Fix a bug where getting repository data using the `RepoClient.getRepo()`  function only works if the name of the repository is all lowercase.

### Acceptance Criteria

```[tasklist]
### The items to complete in order to satisfy the Definition of Done.
- [x] Bug fixed
- [x] Fix release notes file for release v1.0.0-preview.6
- [x] Update release notes in GitHub release for release v1.0.0-preview.6
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
