### ISSUE TITLE
🚧Add options to get variables function

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#43]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add some options to the `getVariables()` function in the `RepoClient` and `OrgClient` class.  These options will be used to signify how to trim the variable values.

**Add the following options:**
1. Add the ability to trim spaces, `\n`, and `\r` characters from the beginning and end of the variable values.
2. Add the ability to return all of the values in uppercase or lowercase

Each option should represent a different trimming behavior.

**Here are the trimming behaviors:**
```ts
/**
 * Represents different carriage return and/or line feed trimming types.
 */
export type TrimType = 
    "TrimStart" |
    "TrimEnd" |
    "TrimBoth" |
    "None";
```

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] All tirmming options created
- [x] Add option to lowercase all values
- [x] Add option to uppercase all values
- [x] The options function parameter should be undefined by default
- [x] Options parameter added to the `RepoClient`
- [x] Options parameter added to the `OrgClient`
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
