### ISSUE TITLE
🚧Update code check steps

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#63]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update all of the code check steps to all execute even if they fail.  Failure will be performed in another new step that will analyze the results of the code check steps. If any of them fail, then the whole workflow will failed.

**Reason:**
This is to allow runs to know if any of the other code checks have failed even if one code check has failed.

The code check steps to update are:
1. Run Lint
2. Run Tests
3. Run Build

These steps will be changed to use the `continue-on-error: true` setting so that way they do not fail the workflow if the check fails.

Refactorings:
1. Refactor the name of the `Run Build` step to `Deno Check`
2. Refactor the name of the `Run Lint` step to `Deno Lint`

Things to add:
1. Add a new step for running deno format checking.
    - The name of the step will be `Deno Format`
    - Use the command `deno fmt --check`
    - This step will also use the `continue-on-error: true` setting
2. After all of the code check steps, add a new step named `Validate Checks` that will check all of the previous code check steps to see if they have failed.  If any of them has failed, the entire workflow will fail.
    - This step should print a GitHub error message of all the steps that have failed.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All unit tests executed and passed locally after PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] `Run Lint` step changed to use the `continue-on-error: true` setting
- [x] `Run Tests` step changed to use the `continue-on-error: true` setting
- [x] `Run Build` step changed to use the `continue-on-error: true` setting
- [x] `Run Build` step renamed to `Deno Check`
- [x] `Run Lint` step renamed to `Deno Lint`
- [x] New step named `Deno Format` added to the list of code checks
- [x] New step named `Validate Checks` added to validate all previous steps
- [x] New `Validate Checks` step prints results of each code check step
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking changes`      |
| New Feature              | `✨new feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
