### ISSUE TITLE
🚧Create default module for models

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#8]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Create a default _**mod.ts**_ module for the models in the `Models` and `Models/GraphQlModels` directories.

The **GraphQL** modules should be also imported into the `Models` folder and reexported.  This will give the option to the user to point to the `Models` _**mod.ts**_ module and get every single model or to reference the _**mod.ts**_ module for the **GraphQL** modules only.

### Acceptance Criteria

- [ ] default module added to the `Models/GraphQlModels` directory
- [ ] default module added to the `Models` directory
    - [ ] `Models/GraphQlModels` _**mod.ts**_ imported into the 

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [ ] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
