### ISSUE TITLE
🚧Refactor function parameter names

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#84]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Refactor parameter names for various functions in the `RepoClient` class and sanitize incoming relative file paths:
This is to make the meaning of the parameters more clear, which in turn improves the API.

**Do the following:**
1. Rename the `branchName` parameter to `ref` for the following functions in the `RepoClient`:
    - `getFileContent`
    - `fileExists`
    - `getFileContentInternal`
2. Update the code docs for the parameters.
3. ~Sanitize the `relativeFilePath` parameters by trimming any `.`, `/`, `\`, and `~` characters from the beginning of the paths.
    This ensures that using these common characters for paths does not cause issues with the URL's construction during the concatenation of the URL and the relative file path. Also, make sure that the URL's `owner/repo/contents` section and the relative file path are separated by a `/` character.~
4. ~Remove the check of absolute file paths from the functions. Refer to the check below~.

### Acceptance Criteria

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] All the unit tests have been executed and passed locally after the PR work is complete. _(Why? Refer to 'Additional Information' below.)_
- [x] Function param names refactored
- [x] ~Incoming relative path sanitized~
- [x] ~The `isAbsolute()` check removed from functions~
```

### ToDo Items

```[tasklist]
### The items to complete to satisfy the Definition of Done.
- [x] Add a change type label to the issue. Refer to the _**Change Type Labels**_ section below.
- [x] Add a priority label to the issue. Refer to the _**Priority Type Labels**_ section below.
- [x] Link the issue to the correct milestone _(if applicable)_.
```

### Additional Information:

**_<details closed><summary>Unit Tests</summary>_**

Reasons for local unit test execution:
- Unit tests might pass locally but not in the CI environment during the status check process or vice-versa.
- Tests might pass on the developer's machine but not necessarily on the code reviewer's machine.
- If you notice that the test status check has passed but the test failed locally, please notify a project maintainer!

💡Warning💡
If the unit tests pass remotely and are not executed locally, this means we could be letting a bug slip into production.
Though bugs will always exist in some capacity, we should all do our part to help prevent them from happening.
</details>

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type              | Label                     |
|:-------------------------|:--------------------------|
| Bug Fixes                | `🐛bug`                   |
| Breaking Changes         | `🧨breaking-changes`      |
| New Feature              | `✨new-feature`           |
| CICD Changes             | `♻️cicd`                  |
| Config Changes           | `⚙️config`                |
| Performance Improvements | `🏎️performance`           |
| Code Doc Changes         | `🗒️documentation/code`    |
| Product Doc Changes      | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Sanitation of the relative file path was fixed in the bug issue below:
- #91
