### ISSUE TITLE
🚧Update clients to check for authentication issues

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/kd_clients#9]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Currently, a lot of the GitHub clients do not specifically catch an authentication HTTP status code of _**403**_ or something similar.

Fix this by going through each GitHub client to properly check for this error, and throwing a proper authentication error.  The error to throw should be a custom authentication error named `AuthError`.  The error should have the default message inherited from `Error`, but also have a property named `InnerErrorMessage`, which represents the original error from the API.

> [!Note]
> Refer to the GitHub REST API docs to get info about authentication error results.

**Example:**
A good example of this is the `RepoClient.getVariables()` function.  This function makes the HTTP REST API call, but it only checks if the returned status code is not equal to OK, and that is it.  This means if an authentication error is returned, it will still return the same non-informative error and the user will not know that it is an authentication error.

https://github.com/KinsonDigital/kd_clients/blob/a8face43589c5bd06a1661c9f3649e7df99e9e0c/GitHubClients/RepoClient.ts#L178-L197

### Acceptance Criteria

```[tasklist]
### The following clients are refactored to deal with auth errors
- [x] Custom error type created for handling authentication errors
- [x] GitClient
- [x] IssueClient
- [x] LabelClient
- [x] MilestoneClient
- [x] OrgClient
- [x] ProjectClient
- [x] PullRequestClient
- [x] ReleaseClient
- [x] RepoClient
- [x] TagClient
- [x] UsersClient
- [x] WorkflowClient
- [x] All `==` replace with `===`
- [x] All `!=`  replaced with `!==`
```

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct milestone _(if applicable)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                |
|---------------------|----------------------|
| Bug Fixes           | `🐛bug` |
| Breaking Changes    | `🧨breaking changes` |
| New Feature         | `✨new feature` |
| CICD Changes        | `♻️cicd` |
| Config Changes      | `⚙️config` |
| Performance Improvements | `🏎️performance` |
| Code Doc Changes    | `🗒️documentation/code` |
| Product Doc Changes | `📝documentation/product` |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label             |
|---------------------|-------------------|
| Low Priority        | `low priority`    |
| Medium Priority     | `medium priority` |
| High Priority       | `high priority`   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
